Mali related Kconfig fix
Compiling with MALI throws this new error:
drivers/gpu/mali/mali/common/mali_kernel_core.c:1084:4: error: implicit
declaration of function 'sync_fence_cancel_async'

That function, which is called because in this new kernel CONFIG_SYNC is
forced by PLAT_RK, should be implemented in /drivers/base/sync.c (see http://lists.linaro.org/pipermail/linaro-
mm-sig/2012-June/002050.html) but it's missing in that file in current
kernel.

Since the Mali driver is the only one that uses CONFIG_SYNC, SW_SYNC*
and it has always worked without them, I'm removing the new dependences.